apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deploy
  labels:
    app: insuranceapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insuranceapp
  template:
    metadata:
      labels:
        app: insuranceapp
    spec:
      containers:
      - name: insurance-container
        image: skbrnrgr/insuranceapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-service
  labels:
    app: insuranceapp
spec:
  selector:
    app: insuranceapp
  type: NodePort
  ports:
  - nodePort: 31997
    port: 8080
    targetPort: 8080
